### ISSUE TITLE
Can be the gateway code generation fully automated?

### ISSUE THREAD

**Issue by NadiaHG** [seronet-project/SeRoNet-Tooling-ROS-Mixed-Port#10]
Now the user has to complete this line:

https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/blob/ffbe249cf9972a5698d9f0d4de23d845092a446a/de.seronet_projekt.xtend.ROS.generator/src/de/seronet_projekt/xtend/ROS/generator/ROS_Callbacks.xtend#L143

is it possible to automate this? otherwise we will have to add here a protected area for the Xtend generator.

**Comment by alex-lotz** [comment]
The comment is probably a bit misleading. The user must not implement this method, but he can if he wants to. This part cannot be automated as this is the actual part where the user code has to be placed which is by definition not generated.

**Comment by alex-lotz** [comment]
I changed the comment in the code generator as follows:

```
// for implementing this method, you can use the "COMP->" macro to access the component's class members
```
I will will do a PR when something more substantial comes.
