### ISSUE TITLE
Get an error by executing the Joystick example

### ISSUE THREAD

**Issue by NadiaHG** [seronet-project/SeRoNet-Tooling-ROS-Mixed-Port#9]
First question:

should [this tutorial](https://wiki.servicerobotik-ulm.de/tutorials:ros:mixed-port-component-ros) still work? 

If yes, I get the following error by executing the script `./startSmartSoftNamingService` :

```
load ns_config.ini parameter file
SmartIniParameter: error: couldn't find parameter file <ns_config.ini>
SmartIniParameter: error: couldn't find parameter file <ns_config.ini>
```

**Comment by dstampfer** [comment]
The tutorial works anyway. The "error" can be ignored; it is rather a warning. Will be fixed upstream.

**Comment by alex-lotz** [comment]
The message in the NamingService has been refined in the last update of the smartsoft kernel: https://github.com/Servicerobotics-Ulm/AceSmartSoftFramework/commit/44cfe4e72c16bf2b6eb38e4c0a0c4e6acd2a86a5
